name: Backport merged pull request
on:
  pull_request_target:
    types: ["labeled", "closed"]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    steps:
      - name: Echo github obj
        run: echo ${{ toJson(github) }}
      # - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v2
      - with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        auto_backport_label_prefix: backport-to-release-list-webview
        source_branch: "master"
        target_branches: "test-list-webview"
        branch_name: "backport/from-{{source_branch}}-to-{{target_branch}}"